# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8-YMTS-MXQqlADvQO1EmmIyYtPTt7x5
"""

import streamlit as st
import pandas as pd
import joblib

model = joblib.load("rfm_classifier.pkl")
scaler = joblib.load("rfm_scaler.pkl")

st.set_page_config(page_title="Customer Segment Predictor", page_icon="🛍️")
st.title("🛍️ Customer Segment Predictor")
st.markdown("Enter customer RFM values to predict the segment.")

recency = st.number_input("Recency (days since last purchase)", min_value=0, value=30)
frequency = st.number_input("Frequency (number of purchases)", min_value=0, value=5)
monetary = st.number_input("Monetary (total spend)", min_value=0, value=500)

if st.button("Predict Segment"):
    input_data = pd.DataFrame({
        'Recency': [recency],
        'Frequency': [frequency],
        'Monetary': [monetary]
    })
    scaled_data = scaler.transform(input_data)
    prediction = model.predict(scaled_data)[0]

    st.success(f"📊 Predicted Segment: Cluster {prediction}")

    segment_info = {
        0: "💎 High-value loyal customer. Keep engaged!",
        1: "🛍️ Average customer. Could be nurtured.",
        2: "📉 At-risk customer. Consider reactivation.",
        3: "🚨 Low-value and inactive customer.",
        4: "🔄 Recent buyer. Watch for loyalty."
    }

    st.info(segment_info.get(prediction, "Segment interpretation unavailable."))